[workspace]
members = [
    "manager",
]
resolver = "2"

[workspace.package]
version = "1.5.0"
edition = "2021"
authors = ["Team DarkCore"]

[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = 3     # Optimize for SPEED (was "z" for size).
lto = "fat"       # Enable Link Time Optimization (Maximum).
codegen-units = 1 # Maximum optimization (slower build).
panic = "abort"   # Remove unwind tables for smaller/faster binary.
